### PR TITLE
Update Program.cs

### PR DESCRIPTION
**Pull request by AlpineJBoehnen**

### CODE REVIEW

**Comment by 0324bence** [comment]
The startpos line is clever, but the endpos line doesn't work (At least when I tried it)

**Comment by AlpineJBoehnen** [comment]
My bad, I think I was off by one on endPos

**Comment by 0324bence** [comment]
Can you actually run it? On my end, it gives an error when the function returns the same position for end and start

**Comment by 0324bence** [comment]
I think the additions on the endPos line are not necessary, and do not work. Please fix

**Comment by AlpineJBoehnen** [comment]
Try that

**Comment by 0324bence** [comment]
Okay, It now produces the same wrong answer but before, but thanks, gonna merge it

**Comment by AlpineJBoehnen** [comment]
The only other thing I can think of is maybe your hashset is preventing valid numbers from being counted, for example: 122 could be {12,2} or {1,22}, I would suggest trying to remove the if on line 31. Good luck

**Pull request merged**
